### ISSUE TITLE
Can't run the official migrado image without TOML config

### ISSUE THREAD

**Issue by Nargonath** [protojour/migrado#10]
I try to run:

```shell
 docker run \
    --mount type=bind,source=./,target=/app \
    -e MIGRADO_DB \
    -e MIGRADO_HOST \
    -e MIGRADO_USER \
    -e MIGRADO_PASS \
    --rm \
    protojour/migrado run
```

But I get the following result: `Poetry could not find a pyproject.toml file in /app or its parents`.

Perhaps I got something wrong but I don't think my project should have a `poetry` config file as I don't use it. That's an implementation detail from migrado and shouldn't leak to userland IMO.

**Comment by tangram** [comment]
You are mounting the local directory `./` into the `/app` directory of the container, overwriting it. This is the `WORKDIR` the image uses. Poetry is used on the inside of the container for dependency management and to have the expected Python environment.

Your project does not need a `pyproject.toml` (not specific to Poetry), and you won't notice Poetry if left alone, but this is more a case of userland leaking into the container.

If you want to mount some directory into the container, you should do so to a subdirectory of `/app`. Migrado only specifically needs the `migrations` directory when running in a Docker context, and expects this to be at `/app/migrations`.

**Comment by Nargonath** [comment]
Alright, my bad. Thanks for the explanation.

**Comment by Nargonath** [comment]
By the way the reason I mounted the project root into the container is because we use the Dockerfile to run migrado as the entrypoint so when you want to use a `schema.yml` for `migrado init` it needs to be in the image. I know I could have mounted only this file or copy/add it during image build but it was simpler just to bind mount the project root.
