### ISSUE TITLE
Arango & ArangoSH running in docker

### ISSUE THREAD

**Issue by incorvia** [protojour/migrado#2]
It seems that when I run this, it attempts to find an arangosh script. However, I'm running arangodb in Docker so arangosh isn't immediately available to the script. Any suggestions on how to resolve this?

**Comment by tangram** [comment]
Migrado was originally designed to be used only from within a Docker context, but we opted to drop this requirement in 8958de1 (0.5.2). It is currently used as part of a web framework where arangosh is available.

To use Migrado on its own with Docker containers, you could either install arangosh, or run Migrado itself from a Docker container, e.g. using something akin to the [Dockerfile](/protojour/migrado/blob/master/Dockerfile) used for testing.

I believe arangosh itself actually uses the ArangoDB HTTP API, so arangosh may not actually be a hard requirement. Scripts can be run against [/_admin/execute](https://www.arangodb.com/docs/stable/http/miscellaneous-functions.html#execute-program) with certain limitations. Give me a couple of hours, and I'll add some alternatives.

**Comment by tangram** [comment]
I had a little trouble with a [PyPI issue](https://status.python.org/), but I've added a public Docker image, built from [this Dockerfile](/protojour/migrado/blob/master/Dockerfile), and a section in the [README](/protojour/migrado/blob/master/README.md#docker-usage) on Docker usage.

I'll look into dropping arangosh altogether, but feel free to close if this resolves the issue for you.

**Comment by incorvia** [comment]
Thanks for taking the time to do that. Very kind of you. This definitely closes out the issue as I was able to run the script from docker as you have illustrated in the readme.
